//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interactive_sign.Resources.StringLocalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class uitext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal uitext() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interactive_sign.Resources.StringLocalisation.uitext", typeof(uitext).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bionic Reading.
        /// </summary>
        internal static string AccessibilityBionicReading {
            get {
                return ResourceManager.GetString("AccessibilityBionicReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the on/off buttons to toggle settings.
        /// </summary>
        internal static string AccessibilityGuidanceMessage {
            get {
                return ResourceManager.GetString("AccessibilityGuidanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reader.
        /// </summary>
        internal static string AccessibilityScreenReader {
            get {
                return ResourceManager.GetString("AccessibilityScreenReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string AccessibilitySettingText {
            get {
                return ResourceManager.GetString("AccessibilitySettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string FontSizeSettingText {
            get {
                return ResourceManager.GetString("FontSizeSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpSettingText {
            get {
                return ResourceManager.GetString("HelpSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Map.
        /// </summary>
        internal static string MapMoveMap {
            get {
                return ResourceManager.GetString("MapMoveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where am I?.
        /// </summary>
        internal static string MapWhereAmI {
            get {
                return ResourceManager.GetString("MapWhereAmI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string MapZoomIn {
            get {
                return ResourceManager.GetString("MapZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string MapZoomOut {
            get {
                return ResourceManager.GetString("MapZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the buttons on the left and right to make this comfortable to read.
        /// </summary>
        internal static string ScaleAdjustableText {
            get {
                return ResourceManager.GetString("ScaleAdjustableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minchel Sminth Shopping Centre.
        /// </summary>
        internal static string ShoppingCentreName {
            get {
                return ResourceManager.GetString("ShoppingCentreName", resourceCulture);
            }
        }
    }
}
